CC = gcc
FLAGS = -Wall

all: 
	$(CC) $(FLAGS) -o ./zad1/main ./zad1/main.c


zad1:
	$(CC) $(FLAGS) -o ./zad1/main ./zad1/main.c
	./zad/main $(operation)

zad2:
	$(CC) $(FLAGS) -o ./zad2/main ./zad2/main.c

clean:
	rm -rf ./zad1/main ./zad2/main


